In [1]:
import numpy as np
x=np.array(((1,1,1),(1,-1,1),(-1,1,1),(-1,-1,1)))
y=np.array((1,-1,-1,-1))
w=np.array((0,0,0))

for i in range(0,4):
    h_w= np.dot(x[i],y[i])
    w=w + h_w
    print (w)

[1 1 1]
[0 2 0]
[ 1  1 -1]
[ 2  2 -2]


In [2]:
test_cases = [(-1, -1), (-1, 1), (1, -1), (1, 1)]
w1,w2= 1,1
threshold = 2

def cal(inputs):
    a,b=inputs
    v = (w1*a) + (w2*b)
    if (v>=threshold):
        return 1
    else:
        return 0
for inputs in test_cases:
    output = cal(inputs)
    print(f"Inputs: {inputs}, Output: {output}")

Inputs: (-1, -1), Output: 0
Inputs: (-1, 1), Output: 0
Inputs: (1, -1), Output: 0
Inputs: (1, 1), Output: 1
