# ONE HOT ENCODING

In [1]:
from sklearn.preprocessing import OneHotEncoder
# Example data
data = [['red'], ['green'], ['blue'], ['green'], ['blue'], ['red']]
# Initialize the encoder
encoder = OneHotEncoder(sparse_output=False)
# Fit and transform the data
one_hot_encoded_data = encoder.fit_transform(data)
print(one_hot_encoded_data)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


# ONE HOT ENCODING ON DATAFRAME

In [2]:
import pandas as pd
# Example data
df = pd.DataFrame({'color': ['red', 'green', 'blue', 'green', 'blue', 'red']})
# One-hot encoding
one_hot_encoded_data = pd.get_dummies(df, columns=['color'])
print(one_hot_encoded_data)


   color_blue  color_green  color_red
0       False        False       True
1       False         True      False
2        True        False      False
3       False         True      False
4        True        False      False
5       False        False       True


# LOG TRANSFORMATION ON SINGLE COLUMN

In [3]:
import pandas as pd
import numpy as np
# Example DataFrame
df = pd.DataFrame({
 'A': [1, 10, 100, 1000, 10000],
 'B': [5, 15, 25, 35, 45]
})
# Apply log transformation to column 'A'
df['A_log'] = np.log(df['A'])
print(df)

       A   B     A_log
0      1   5  0.000000
1     10  15  2.302585
2    100  25  4.605170
3   1000  35  6.907755
4  10000  45  9.210340


# NORMALIZE USING MINMAXSCALER

In [4]:
from sklearn.preprocessing import MinMaxScaler
# Example data
data = [[1], [2], [3], [4], [5]]
# Initialize the scaler
scaler = MinMaxScaler()
# Fit and transform the data
normalized_data = scaler.fit_transform(data)
print(normalized_data)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


# STANDARDIZATION USING STANDARDSCLAR

In [5]:
from sklearn.preprocessing import StandardScaler
# Example data
data = [[1], [2], [3], [4], [5]]
# Initialize the scaler
scaler = StandardScaler()
# Fit and transform the data
standardized_data = scaler.fit_transform(data)
print(standardized_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]
